<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_healthcare_programs_block',
    'title' => 'Healthcare Programs Block Fields',
    'fields' => array(
        array(
            'key' => 'field_story_card_heading',
            'label' => 'Story Card Heading',
            'name' => 'story_card_heading',
            'type' => 'text',
            'instructions' => 'Enter the heading for the story card section',
            'required' => 0,
        ),
        array(
            'key' => 'field_story_card_description',
            'label' => 'Story Card Description',
            'name' => 'story_card_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description text for the story card',
            'required' => 0,
            'rows' => 2,
        ),
        array(
            'key' => 'field_story_card_link_text',
            'label' => 'Story Card Link Text',
            'name' => 'story_card_link_text',
            'type' => 'text',
            'instructions' => 'Enter the text for the story card link button',
            'required' => 0,
        ),
        array(
            'key' => 'field_story_card_link',
            'label' => 'Story Card Link URL',
            'name' => 'story_card_link',
            'type' => 'url',
            'instructions' => 'Enter the URL for the story card link',
            'required' => 0,
        ),
        array(
            'key' => 'field_story_card_background_image',
            'label' => 'Story Card Background Image',
            'name' => 'story_card_background_image',
            'type' => 'image',
            'instructions' => 'Upload a background image for the story card',
            'required' => 0,
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
        ),
        array(
            'key' => 'field_healthcare_headline',
            'label' => 'Main Headline',
            'name' => 'healthcare_headline',
            'type' => 'text',
            'instructions' => 'Enter the main headline for the hero section',
            'required' => 1,
        ),
        array(
            'key' => 'field_program_tabs',
            'label' => 'Program Tabs',
            'name' => 'program_tabs',
            'type' => 'repeater',
            'instructions' => 'Add program tabs with their content',
            'required' => 1,
            'min' => 1,
            'max' => 6,
            'layout' => 'block',
            'button_label' => 'Add Program Tab',
            'sub_fields' => array(
                array(
                    'key' => 'field_tab_name',
                    'label' => 'Tab Name',
                    'name' => 'tab_name',
                    'type' => 'text',
                    'instructions' => 'Enter the program tab name',
                    'required' => 1,
                ),
                array(
                    'key' => 'field_tab_program_headline',
                    'label' => 'Program Headline',
                    'name' => 'tab_program_headline',
                    'type' => 'text',
                    'instructions' => 'Enter the program headline for this tab',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_program_description',
                    'label' => 'Program Description',
                    'name' => 'tab_program_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter the program description for this tab',
                    'required' => 0,
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_tab_learn_more_link',
                    'label' => 'Learn More Link',
                    'name' => 'tab_learn_more_link',
                    'type' => 'url',
                    'instructions' => 'Enter the URL for the "Learn more" link',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_nclex_label',
                    'label' => 'NCLEX Label',
                    'name' => 'tab_nclex_label',
                    'type' => 'text',
                    'instructions' => 'Enter the NCLEX label text',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_nclex_rate',
                    'label' => 'NCLEX Pass Rate',
                    'name' => 'tab_nclex_rate',
                    'type' => 'text',
                    'instructions' => 'Enter the NCLEX pass rate percentage',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_nclex_source',
                    'label' => 'NCLEX Source',
                    'name' => 'tab_nclex_source',
                    'type' => 'text',
                    'instructions' => 'Enter the source text for NCLEX data',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_program_outcomes_link',
                    'label' => 'Program Outcomes Link',
                    'name' => 'tab_program_outcomes_link',
                    'type' => 'url',
                    'instructions' => 'Enter the URL for the "View all Program Outcomes" link',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_testimonial_text',
                    'label' => 'Testimonial Text',
                    'name' => 'tab_testimonial_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the testimonial text for this tab',
                    'required' => 0,
                    'rows' => 3,
                ),
                array(
                    'key' => 'field_tab_testimonial_name',
                    'label' => 'Testimonial Name',
                    'name' => 'tab_testimonial_name',
                    'type' => 'text',
                    'instructions' => 'Enter the testimonial author name',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_testimonial_title',
                    'label' => 'Testimonial Title',
                    'name' => 'tab_testimonial_title',
                    'type' => 'text',
                    'instructions' => 'Enter the testimonial author title',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_read_more_link',
                    'label' => 'Read More Link',
                    'name' => 'tab_read_more_link',
                    'type' => 'url',
                    'instructions' => 'Enter the URL for the "Read more" link',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_testimonial_background_image',
                    'label' => 'Testimonial Card Background Image',
                    'name' => 'tab_testimonial_background_image',
                    'type' => 'image',
                    'instructions' => 'Upload a background image for the testimonial card',
                    'required' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_tab_video_file',
                    'label' => 'Video File (Upload from Library)',
                    'name' => 'tab_video_file',
                    'type' => 'file',
                    'instructions' => 'Upload a video file from your media library (MP4, WebM, etc.)',
                    'required' => 0,
                    'return_format' => 'array',
                    'library' => 'all',
                    'mime_types' => 'mp4,webm,ogg,mov',
                ),
                array(
                    'key' => 'field_tab_video_url',
                    'label' => 'Video URL (External)',
                    'name' => 'tab_video_url',
                    'type' => 'url',
                    'instructions' => 'OR enter an external video URL (YouTube, Vimeo, etc.). Video file upload takes priority if both are provided.',
                    'required' => 0,
                ),
                array(
                    'key' => 'field_tab_video_thumbnail',
                    'label' => 'Video Thumbnail/Poster Image',
                    'name' => 'tab_video_thumbnail',
                    'type' => 'image',
                    'instructions' => 'Upload a custom thumbnail/poster image for the video. This will be shown before the video plays. Recommended for uploaded videos. YouTube videos auto-generate thumbnails.',
                    'required' => 0,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
            ),
        ),
        array(
            'key' => 'field_all_programs_link',
            'label' => 'All Programs Link',
            'name' => 'all_programs_link',
            'type' => 'url',
            'instructions' => 'Enter the URL for the "All programs" link',
            'required' => 0,
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/healthcare-programs',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
));

endif;
