<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_hero_get_started',
    'title' => 'Hero Get Started Block Fields',
    'fields' => array(
        array(
            'key' => 'field_hero_get_started_heading',
            'label' => 'Heading Text',
            'name' => 'hero_get_started_heading',
            'type' => 'text',
            'instructions' => 'Enter the main heading text for the block.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Get started today.',
            'placeholder' => 'Get started today.',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_hero_get_started_programs',
            'label' => 'Program Options',
            'name' => 'hero_get_started_programs',
            'type' => 'repeater',
            'instructions' => 'Add program options for the dropdown menu.',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'collapsed' => 'field_program_name',
            'min' => 1,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Program',
            'sub_fields' => array(
                array(
                    'key' => 'field_program_name',
                    'label' => 'Program Name',
                    'name' => 'program_name',
                    'type' => 'text',
                    'instructions' => 'Enter the program name.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'e.g., Web Development',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_program_value',
                    'label' => 'Program Value',
                    'name' => 'program_value',
                    'type' => 'text',
                    'instructions' => 'Enter the program value (used in form submission).',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'web-development',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_hero_get_started_placeholder',
            'label' => 'Dropdown Placeholder',
            'name' => 'hero_get_started_placeholder',
            'type' => 'text',
            'instructions' => 'Enter the placeholder text for the dropdown.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'What is your program of interest?',
            'placeholder' => 'What is your program of interest?',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_hero_get_started_button_text',
            'label' => 'Button Text',
            'name' => 'hero_get_started_button_text',
            'type' => 'text',
            'instructions' => 'Enter the button text.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Next',
            'placeholder' => 'Next',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_hero_get_started_action_url',
            'label' => 'Form Action URL',
            'name' => 'hero_get_started_action_url',
            'type' => 'url',
            'instructions' => 'Enter the URL where the form should be submitted (optional).',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'https://example.com/form-handler',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/hero-get-started',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Fields for the Hero Get Started block.',
));

endif;
