<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_accreditations_approvals',
    'title' => 'Accreditations & Approvals Block',
    'fields' => array(
        array(
            'key' => 'field_accreditations_title',
            'label' => 'Title',
            'name' => 'accreditations_title',
            'type' => 'text',
            'instructions' => 'Enter the main title for the accreditations section',
            'required' => 1,
            'placeholder' => 'Enter title text',
            'maxlength' => 100,
        ),
        array(
            'key' => 'field_accreditations_description',
            'label' => 'Description',
            'name' => 'accreditations_description',
            'type' => 'textarea',
            'instructions' => 'Enter the description text',
            'required' => 1,
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_accreditations_view_all_text',
            'label' => 'View All Link Text',
            'name' => 'accreditations_view_all_text',
            'type' => 'text',
            'instructions' => 'Enter the text for the "View all" link',
            'required' => 0,
            'default_value' => 'View all',
            'placeholder' => 'Enter link text',
            'maxlength' => 50,
        ),
        array(
            'key' => 'field_accreditations_view_all_url',
            'label' => 'View All Link URL',
            'name' => 'accreditations_view_all_url',
            'type' => 'url',
            'instructions' => 'Enter the URL for the "View all" link',
            'required' => 0,
            'placeholder' => 'https://example.com',
        ),
        array(
            'key' => 'field_accreditations_items',
            'label' => 'Accreditation Items',
            'name' => 'accreditations_items',
            'type' => 'repeater',
            'instructions' => 'Add accreditation items to display',
            'required' => 1,
            'min' => 1,
            'max' => 6,
            'layout' => 'table',
            'button_label' => 'Add Accreditation Item',
            'sub_fields' => array(
                array(
                    'key' => 'field_accreditation_logo',
                    'label' => 'Logo/Image',
                    'name' => 'accreditation_logo',
                    'type' => 'image',
                    'instructions' => 'Upload the accreditation logo or image',
                    'required' => 1,
                    'return_format' => 'array',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_accreditation_title',
                    'label' => 'Title/Name',
                    'name' => 'accreditation_title',
                    'type' => 'text',
                    'instructions' => 'Enter the accreditation title or name',
                    'required' => 0,
                    'placeholder' => 'Enter accreditation title',
                    'maxlength' => 100,
                ),
                array(
                    'key' => 'field_accreditation_description',
                    'label' => 'Description',
                    'name' => 'accreditation_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter the accreditation description',
                    'required' => 1,
                    'placeholder' => 'Enter accreditation description',
                    'rows' => 2,
                    'new_lines' => 'br',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/accreditations-approvals',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Accreditations & Approvals section with logo items and view all link',
));

endif;
