<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_unitek_advantage',
    'title' => 'Unitek Advantage Block',
    'fields' => array(
        array(
            'key' => 'field_unitek_advantage_heading',
            'label' => 'Heading',
            'name' => 'unitek_advantage_heading',
            'type' => 'text',
            'instructions' => 'Enter the main heading for the advantage section',
            'required' => 1,
            'default_value' => 'The Unitek advantage.',
            'placeholder' => 'Enter heading text',
            'maxlength' => 100,
        ),
        array(
            'key' => 'field_unitek_advantage_subheading',
            'label' => 'Subheading / Intro Text',
            'name' => 'unitek_advantage_subheading',
            'type' => 'textarea',
            'instructions' => 'Enter the introductory text',
            'required' => 1,
            'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_unitek_advantage_body_text',
            'label' => 'Body Text',
            'name' => 'unitek_advantage_body_text',
            'type' => 'textarea',
            'instructions' => 'Enter the main body text',
            'required' => 1,
            'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
            'rows' => 4,
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_unitek_advantage_features',
            'label' => 'Features',
            'name' => 'unitek_advantage_features',
            'type' => 'repeater',
            'instructions' => 'Add up to 3 features to display in columns',
            'required' => 1,
            'min' => 3,
            'max' => 3,
            'layout' => 'table',
            'button_label' => 'Add Feature',
            'sub_fields' => array(
                array(
                    'key' => 'field_unitek_advantage_feature_title',
                    'label' => 'Feature Title',
                    'name' => 'feature_title',
                    'type' => 'text',
                    'instructions' => 'Enter the feature title (will be displayed in uppercase)',
                    'required' => 1,
                    'placeholder' => 'REAL-WORLD EXPERIENCE.',
                    'maxlength' => 50,
                ),
                array(
                    'key' => 'field_unitek_advantage_feature_description',
                    'label' => 'Feature Description',
                    'name' => 'feature_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter the feature description',
                    'required' => 1,
                    'placeholder' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                    'rows' => 2,
                    'new_lines' => 'br',
                ),
                array(
                    'key' => 'field_unitek_advantage_feature_url',
                    'label' => 'Feature URL',
                    'name' => 'feature_url',
                    'type' => 'url',
                    'instructions' => 'Enter the URL for this feature (optional)',
                    'required' => 0,
                    'placeholder' => 'https://example.com',
                ),
            ),
        ),
        array(
            'key' => 'field_unitek_advantage_cta_text',
            'label' => 'CTA Button Text',
            'name' => 'unitek_advantage_cta_text',
            'type' => 'text',
            'instructions' => 'Enter the call-to-action button text',
            'required' => 0,
            'default_value' => 'Get started today',
            'placeholder' => 'Enter button text',
            'maxlength' => 50,
        ),
        array(
            'key' => 'field_unitek_advantage_cta_url',
            'label' => 'CTA Button URL',
            'name' => 'unitek_advantage_cta_url',
            'type' => 'url',
            'instructions' => 'Enter the call-to-action button URL',
            'required' => 0,
            'placeholder' => 'https://example.com',
        ),
        array(
            'key' => 'field_unitek_advantage_testimonial_category',
            'label' => 'Testimonial Category',
            'name' => 'unitek_advantage_testimonial_category',
            'type' => 'taxonomy',
            'instructions' => 'Select a category. All testimonials will be from this category only.',
            'required' => 1,
            'taxonomy' => 'testimonial_category',
            'field_type' => 'select',
            'allow_null' => 0,
            'add_term' => 0,
            'save_terms' => 0,
            'load_terms' => 0,
            'return_format' => 'id',
            'multiple' => 0,
        ),
        array(
            'key' => 'field_unitek_advantage_testimonial_thumbnail',
            'label' => 'Thumbnail Style',
            'name' => 'unitek_advantage_testimonial_thumbnail',
            'type' => 'radio',
            'instructions' => 'Select a thumbnail style. All testimonials will use this same style.',
            'required' => 1,
            'choices' => array(
                'thumbnail_1' => 'Thumbnail 1 (Dark Grey with Light Blue)',
                'thumbnail_2' => 'Thumbnail 2 (Dark Blue with Light Blue)',
                'thumbnail_3' => 'Thumbnail 3 (Dark Grey with Light Green)',
                'thumbnail_4' => 'Thumbnail 4 (Bright Blue with White)',
                'thumbnail_5' => 'Thumbnail 5 (Light Green with White)',
                'thumbnail_6' => 'Thumbnail 6 (Light Green with Dark Grey)',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => 'thumbnail_1',
            'layout' => 'vertical',
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_unitek_advantage_testimonial_number',
            'label' => 'Number of Testimonials',
            'name' => 'unitek_advantage_testimonial_number',
            'type' => 'number',
            'instructions' => 'Enter the number of testimonials to display (1-10)',
            'required' => 0,
            'default_value' => 5,
            'min' => 1,
            'max' => 10,
            'step' => 1,
            'placeholder' => '5',
        ),
        array(
            'key' => 'field_unitek_advantage_testimonial_order',
            'label' => 'Display Order',
            'name' => 'unitek_advantage_testimonial_order',
            'type' => 'select',
            'instructions' => 'Choose the order to display testimonials',
            'required' => 0,
            'choices' => array(
                'DESC' => 'Newest First (Descending)',
                'ASC' => 'Oldest First (Ascending)',
            ),
            'default_value' => 'DESC',
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/unitek-advantage',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Unitek Advantage section with features, CTA button, and testimonial',
));

endif;
