<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_unitek_advantage',
    'title' => 'Unitek Advantage Block',
    'fields' => array(
        array(
            'key' => 'field_unitek_advantage_heading',
            'label' => 'Heading',
            'name' => 'unitek_advantage_heading',
            'type' => 'text',
            'instructions' => 'Enter the main heading for the advantage section',
            'required' => 1,
            'default_value' => 'The Unitek advantage.',
            'placeholder' => 'Enter heading text',
            'maxlength' => 100,
        ),
        array(
            'key' => 'field_unitek_advantage_subheading',
            'label' => 'Subheading / Intro Text',
            'name' => 'unitek_advantage_subheading',
            'type' => 'textarea',
            'instructions' => 'Enter the introductory text',
            'required' => 1,
            'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_unitek_advantage_body_text',
            'label' => 'Body Text',
            'name' => 'unitek_advantage_body_text',
            'type' => 'textarea',
            'instructions' => 'Enter the main body text',
            'required' => 1,
            'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
            'rows' => 4,
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_unitek_advantage_features',
            'label' => 'Features',
            'name' => 'unitek_advantage_features',
            'type' => 'repeater',
            'instructions' => 'Add up to 3 features to display in columns',
            'required' => 1,
            'min' => 3,
            'max' => 3,
            'layout' => 'table',
            'button_label' => 'Add Feature',
            'sub_fields' => array(
                array(
                    'key' => 'field_unitek_advantage_feature_title',
                    'label' => 'Feature Title',
                    'name' => 'feature_title',
                    'type' => 'text',
                    'instructions' => 'Enter the feature title (will be displayed in uppercase)',
                    'required' => 1,
                    'placeholder' => 'REAL-WORLD EXPERIENCE.',
                    'maxlength' => 50,
                ),
                array(
                    'key' => 'field_unitek_advantage_feature_description',
                    'label' => 'Feature Description',
                    'name' => 'feature_description',
                    'type' => 'textarea',
                    'instructions' => 'Enter the feature description',
                    'required' => 1,
                    'placeholder' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                    'rows' => 2,
                    'new_lines' => 'br',
                ),
            ),
        ),
        array(
            'key' => 'field_unitek_advantage_cta_text',
            'label' => 'CTA Button Text',
            'name' => 'unitek_advantage_cta_text',
            'type' => 'text',
            'instructions' => 'Enter the call-to-action button text',
            'required' => 0,
            'default_value' => 'Get started today',
            'placeholder' => 'Enter button text',
            'maxlength' => 50,
        ),
        array(
            'key' => 'field_unitek_advantage_cta_url',
            'label' => 'CTA Button URL',
            'name' => 'unitek_advantage_cta_url',
            'type' => 'url',
            'instructions' => 'Enter the call-to-action button URL',
            'required' => 0,
            'placeholder' => 'https://example.com',
        ),
        array(
            'key' => 'field_unitek_advantage_testimonials',
            'label' => 'Testimonials',
            'name' => 'unitek_advantage_testimonials',
            'type' => 'repeater',
            'instructions' => 'Add testimonials for the carousel (minimum 1, recommended 3)',
            'required' => 1,
            'min' => 1,
            'max' => 5,
            'layout' => 'table',
            'button_label' => 'Add Testimonial',
            'sub_fields' => array(
                array(
                    'key' => 'field_unitek_advantage_testimonial_text',
                    'label' => 'Testimonial Text',
                    'name' => 'testimonial_text',
                    'type' => 'textarea',
                    'instructions' => 'Enter the testimonial quote text',
                    'required' => 1,
                    'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
                    'rows' => 3,
                    'new_lines' => 'br',
                ),
                array(
                    'key' => 'field_unitek_advantage_testimonial_name',
                    'label' => 'Author Name',
                    'name' => 'testimonial_name',
                    'type' => 'text',
                    'instructions' => 'Enter the testimonial author name',
                    'required' => 1,
                    'default_value' => 'Name A.',
                    'placeholder' => 'Enter author name',
                    'maxlength' => 50,
                ),
                array(
                    'key' => 'field_unitek_advantage_testimonial_title',
                    'label' => 'Author Title',
                    'name' => 'testimonial_title',
                    'type' => 'text',
                    'instructions' => 'Enter the testimonial author title/designation',
                    'required' => 1,
                    'default_value' => 'Unitek Graduate',
                    'placeholder' => 'Enter author title',
                    'maxlength' => 50,
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/unitek-advantage',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'Unitek Advantage section with features, CTA button, and testimonial',
));

endif;
